### ISSUE TITLE
Source data is an observable itself

### ISSUE THREAD

**Issue by matheo** [scaljeri/angular-route-xxl#10]
I have used Angular's Router data, params and queryParams, but I'm finding hard to imagine how to setup an observable as the source itself.

I'm needing to communicate some custom arguments through my components, so I'm thinking on a shared Observable able to emit values from one component, and be subscribed by the others. Is that remotely possible? thanks!

**Comment by scaljeri** [comment]
Do you mean with `@RouteTunnel`?  Because angular 5.2 changed something in how the Router works I rewrote this library which can be found [here](https://github.com/scaljeri/angular-xxl)

I also changed `@RouteTunnel` to just `@Tunnel`, decoupled it from the router code. You can see it in action in the [demo](https://stackblitz.com/edit/angular-tunnel?file=app%2Fblock%2Fblock.component.ts) too!

**Comment by matheo** [comment]
Oh man, you saved my life!!
THANKS A LOT!!

Awesome stuff, `@Tunnel` is just what I was looking for!!
Keep it up :D
